AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Name:
    Type: String
    Default: unuse-lambda-proxy-integration-ex-demo

Resources:
    ##   #####  #     ####    ##   ##### ###### #    #   ##   #   #
   #  #  #    # #    #    #  #  #    #   #      #    #  #  #   # #
  #    # #    # #    #      #    #   #   #####  #    # #    #   #
  ###### #####  #    #  ### ######   #   #      # ## # ######   #
  #    # #      #    #    # #    #   #   #      ##  ## #    #   #
  #    # #      #     ####  #    #   #   ###### #    # #    #   #
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref Name
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      HttpMethod: POST
      ResourceId: !Ref RootResource
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ErrHandlerFunction.Arn}/invocations
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: |
            #set($allParams = $input.params())
            {
              #set($params = $allParams.get('querystring'))
              #if($params.isEmpty())
              "queryStringParameters" : null,
              #else
              "queryStringParameters" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #set($params = $allParams.get('header'))
              #if($params.isEmpty())
              "headers" : null,
              #else
              "headers" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #set($params = $allParams.get('path'))
              #if($params.isEmpty())
              "pathParameters" : null,
              #else
              "pathParameters" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #if($input.body == {})
              "body" : null
              #else
              "body" : "$util.escapeJavaScript($input.body)"
              #end
            }
        IntegrationResponses:
        - StatusCode: 200
          ResponseTemplates:
            application/json: |
              $input.path('$.body')
        - StatusCode: 500
          SelectionPattern: ".*message.*"
          ResponseTemplates:
            application/json: |
              $input.path('$.errorMessage')
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 500
  WithRequestPathMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      HttpMethod: POST
      ResourceId: !Ref WithRequestPathResource
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ErrHandlerFunction.Arn}/invocations
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: |
            #set($allParams = $input.params())
            {
              #set($params = $allParams.get('querystring'))
              #if($params.isEmpty())
              "queryStringParameters" : null,
              #else
              "queryStringParameters" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #set($params = $allParams.get('header'))
              #if($params.isEmpty())
              "headers" : null,
              #else
              "headers" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #set($params = $allParams.get('path'))
              #if($params.isEmpty())
              "pathParameters" : null,
              #else
              "pathParameters" : {
                #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext),#end
                #end
              },
              #end
              #if($input.body == {})
              "body" : null
              #else
              "body" : "$util.escapeJavaScript($input.body)"
              #end
            }
        IntegrationResponses:
        - StatusCode: 200
          ResponseTemplates:
            application/json: |
              $input.path('$.body')
        - StatusCode: 500
          SelectionPattern: ".*message.*"
          ResponseTemplates:
            application/json: |
              $input.path('$.errorMessage')
      MethodResponses:
      - StatusCode: 200
      - StatusCode: 500
  RootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: 'example'
  WithRequestPathResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref RootResource
      PathPart: '{val}'
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
    DependsOn:
    - RootMethod
    - WithRequestPathMethod
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiGatewayDeployment
      StageName: v1

  #        ##   #    # #####  #####    ##
  #       #  #  ##  ## #    # #    #  #  #
  #      #    # # ## # #####  #    # #    #
  #      ###### #    # #    # #    # ######
  #      #    # #    # #    # #    # #    #
  ###### #    # #    # #####  #####  #    #
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          # coding: utf-8
          import json
          def handler(event, context):
            print(json.dumps(event))
            try:
              if event.get("body") is not None:
                print(json.dumps(json.loads(event.get("body"))))
              return { "statusCode": 200, "body": json.dumps(event) }
            except Exception as e:
              return { "statusCode": 500, "body": json.dumps({ "message": str(e) }) }
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
  ErrHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          # coding: utf-8
          import json
          import boto3
          client = boto3.client('lambda')
          def handler(event, context):
            print(json.dumps(event))
            response = client.invoke(
              FunctionName = '${LambdaFunction}',
              InvocationType = 'RequestResponse',
              Payload = json.dumps(event).encode()
            )
            payload = json.loads(response['Payload'].read().decode('utf-8'))
            if (payload['statusCode'] == 500):
              raise Exception(payload['body'])
            return payload
      Role: !GetAtt ErrHandlerRole.Arn
      Runtime: python3.7
  RootMethodPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ErrHandlerFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/POST/example"
  WithRequestPathMethodPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ErrHandlerFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/POST/example/{val}"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ErrHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
